name: Deploy to AKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS credentials
      run: |
        az aks get-credentials \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name ${{ secrets.CLUSTER_NAME }} \
          --overwrite-existing
    - name: Verify kubectl context
      run: kubectl config current-context
        
    - name: deploy AKS
      run: |
         kubectl apply -f k8s/deployment.yml
         kubectl apply -f k8s/service.yml
