# deploy to aks

name: Build & deploy to AKS
on:
 workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v5.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'      
    - name: Restore dependencies
      run: dotnet restore githubactions-aks-demo.sln
    - name: Build solution
      run: dotnet build githubactions-aks-demo.sln --configuration release --no-restore
  Docker_build:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v5.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    # 🔐 Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
            
    # 🔐 Login to Azure Container Registry
    - name: Azure ACR Login
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: | 
         rajesh1218/github-actions-aks:'${{github.sha}}'
         devpprojectrajesh.azurecr.io/github-actions-aks:${{ github.sha }}

      
     
     
